# Academic Website Builder
# https://sourcethemes.com/academic/
#
# The presence of this file is for compatibility with Blogdown and Forestry.
# If you are not using those tools, this file may be deleted.
#
# The actual configuration files are stored in the `config/_default/` folder.

baseurl = "https://vpronina.github.io/"
title = "Picasel Agency Docs"
#if not set copyright, default copyright template will be applied
copyright = "Copyright (c) 2008 - 2014, Steve Francia; all rights reserved."
theme = "nofancy"

[params]
	highlight="Assign a syntax highlight style"

[author]
    name = "Komarov Valentin"
    github = "lamberk"
